Repository aarkaynegi/prisma.io-clone, pull requests merged in 2023-09, with the labels that each got.

#2 docs: README.md
  README.md
  public/prisma-readme.png
Labels: documentation

#4 refactor: Header component
  src/components/header/Header.tsx
  src/components/header/HeaderButton.tsx
  src/components/header/HeaderLogo.tsx
  src/components/header/NavBar.tsx
Labels: refactor

#5 ui: landing page design updated
  package.json
  src/App.tsx
  src/components/header/Header.css
  src/components/header/Header.tsx
  src/components/header/NavBar.tsx
  src/components/sections/firstSection/FirstSection.css
  src/components/sections/firstSection/FirstSection.tsx
  src/components/sections/firstSection/Testimonials.tsx
  src/components/sections/hero/Hero.tsx
  src/index.css
Labels: ui design

#6 ui: navbar subsections
  package-lock.json
  package.json
  src/assets/images/nav-playground.svg
  src/assets/images/prisma-logo.svg
  src/components/header/<div>.html
  src/components/header/Header.css
  src/components/header/HeaderButton.tsx
  src/components/header/NavBar.tsx
  src/components/sections/firstSection/FirstSection.tsx
  src/components/sections/firstSection/Testimonials.tsx
Labels: ui design

#9 ui: navbar updated
  public/images/nav-article/nav-article-1.svg
  public/images/nav-article/nav-article-2.svg
  src/components/header/Header.tsx
  src/components/header/NavBar.tsx
Labels: ui design

#10 refactor: minor code refactor
  src/components/sections/firstSection/Testimonials.tsx
  src/components/sections/secondSection/SecondSection.tsx
Labels: refactor

#11 ui: third and fourth section
  src/App.tsx
  src/assets/images/ts-framed.svg
  src/assets/images/typesafe-database-client.svg
  src/assets/images/vscode.svg
  src/components/container/Container.tsx
  src/components/header/<div>.html
  src/components/sections/firstSection/FirstSection.css
  src/components/sections/firstSection/FirstSection.tsx
  src/components/sections/fourthSection/FourthSection.css
  src/components/sections/fourthSection/FourthSection.tsx
  src/components/sections/secondSection/SecondSection.tsx
  src/components/sections/thirdSection/ThirdSection.css
  src/components/sections/thirdSection/ThirdSection.tsx
  src/index.css
Labels: ui design

#12 ui landing page
  src/assets/images/hasslefree-migrations.svg
  src/assets/images/visual-database.svg
  src/components/container/Container.tsx
  src/components/header/Header.tsx
  src/components/sections/fourthSection/FourthSection.tsx
  src/components/sections/hero/Hero.tsx
  src/components/sections/secondSection/SecondSection.tsx
  src/components/sections/thirdSection/ThirdSection.css
  src/components/sections/thirdSection/ThirdSection.tsx
  src/index.tsx
Labels: ui design

#13 ui: fifth section added
  Favour
  src/App.tsx
  src/assets/images/fifthSection/apollo.svg
  src/assets/images/fifthSection/express.svg
  src/assets/images/fifthSection/graphql.svg
  src/assets/images/fifthSection/hapi.svg
  src/assets/images/fifthSection/nest.svg
  src/assets/images/fifthSection/nextjs.svg
  src/assets/images/fourthSection/hasslefree-migrations.svg
  src/assets/images/fourthSection/visual-database.svg
  src/assets/images/hero/hero-lines.svg
  src/assets/images/secondSection/second-section-schema.svg
  src/assets/images/thirdSection/ts-framed.svg
  src/assets/images/thirdSection/typesafe-database-client.svg
  src/assets/images/thirdSection/vscode.svg
  src/components/sections/fifthSection/FavouriteFrameWorks.tsx
  src/components/sections/fifthSection/FifthSection.css
  src/components/sections/fifthSection/FifthSection.tsx
  src/components/sections/fourthSection/FourthSection.tsx
  src/components/sections/secondSection/SecondSection.tsx
  src/components/sections/thirdSection/ThirdSection.tsx
  src/components/svgs/StackDesktop.tsx
  src/components/svgs/StackHhp.tsx
  src/index.css
Labels: refactor, ui design

#14 ui: footer added
  src/App.tsx
  src/components/sections/fifthSection/FifthSection.tsx
  src/components/sections/footer/Footer.css
  src/components/sections/footer/Footer.tsx
  src/components/sections/footer/FooterSection.css
  src/components/sections/footer/FooterSecton.tsx
  src/components/sections/fourthSection/FourthSection.tsx
  src/components/sections/secondSection/SecondSection.css
  src/components/sections/secondSection/SecondSection.tsx
  src/components/sections/thirdSection/ThirdSection.css
  src/components/sections/thirdSection/ThirdSection.tsx
  src/index.css
Labels: ui design

#15 ui: sixth section
  src/App.tsx
  src/assets/images/sixthSection/SixthSectionSVG.css
  src/assets/images/sixthSection/SixthSectionSVG.tsx
  src/assets/images/sixthSection/SixthSectionSVG2.tsx
  src/assets/images/sixthSection/optimise-filter.svg
  src/components/sections/fifthSection/FifthSection.tsx
  src/components/sections/footer/Footer.tsx
  src/components/sections/footer/FooterSecton.tsx
  src/components/sections/footer/footer-data.ts
  src/components/sections/sixthSection/SixthSection.css
  src/components/sections/sixthSection/SixthSection.tsx
  src/components/sections/thirdSection/ThirdSection.tsx
  src/components/svgs/StackDesktop.css
  src/components/svgs/StackDesktop.tsx
  src/components/svgs/StackHhp.css
  src/components/svgs/StackHhp.tsx
Labels: refactor, ui design

#16 refactor: minor refactor
  src/assets/images/sixthSection/SixthSectionSVG.tsx
  src/components/sections/fifthSection/FavouriteFrameWorks.tsx
  src/components/sections/firstSection/Testimonials.tsx
  src/components/sections/footer/Footer.tsx
  src/components/sections/secondSection/SecondSection.tsx
  src/components/sections/sixthSection/SixthSection.css
  src/components/sections/sixthSection/SixthSection.tsx
  src/components/svgs/StackDesktop.tsx
  src/components/svgs/StackHhp.tsx
Labels: refactor

#18 ui: seventh section
  src/App.tsx
  src/assets/images/seventhSection/slider/elsevier.svg
  src/assets/images/seventhSection/slider/gatsby.svg
  src/assets/images/seventhSection/slider/grover.svg
  src/assets/images/seventhSection/slider/ihi.svg
  src/assets/images/seventhSection/slider/insta.svg
  src/assets/images/seventhSection/slider/invisible.svg
  src/assets/images/seventhSection/slider/outrider.svg
  src/assets/images/seventhSection/slider/oxio.svg
  src/assets/images/seventhSection/slider/panther.svg
  src/assets/images/seventhSection/slider/poppy.svg
  src/assets/images/seventhSection/slider/rapha.svg
  src/assets/images/seventhSection/slider/southpole.svg
  src/assets/images/seventhSection/slider/tryg.svg
  src/assets/images/seventhSection/slider/twiga.svg
  src/assets/images/sixthSection/slider/gatsby.svg
  src/components/sections/seventhSection/SeventhSection.css
  src/components/sections/seventhSection/SeventhSection.tsx
  src/components/sections/sixthSection/SixthSection.css
  src/components/sections/sixthSection/SixthSection.tsx
  src/index.css
Labels: ui design

#19 remove: favour file
  Favour
Labels: refactor

#21 ui: header udpate
  src/components/header/Header.tsx
  src/components/header/NavBar.tsx
  src/components/sections/hero/Hero.tsx
  src/components/sections/seventhSection/SeventhSection.css
  src/index.css
Labels: ui design

#22 ui: navbar and hero section update
  src/components/header/HeaderButton.tsx
  src/components/header/NavBar.tsx
  src/components/sections/hero/Hero.css
  src/components/sections/hero/Hero.tsx
Labels: ui design

#23 ui: first section css updated
  src/components/sections/firstSection/FirstSection.tsx
  src/components/sections/firstSection/Testimonials.css
  src/components/sections/firstSection/Testimonials.tsx
  src/components/sections/hero/Hero.tsx
Labels: ui design
